### PR TITLE
morkdownify, use brucedown, github styling

### PR DESCRIPTION
**Pull request by rvagg**
Hey! Thanks so much for stating **me**, since they stopped updating [appjs](http://appjs.org/) (I don't know if it's abandonware or not), [morkdown](https://github.com/rvagg/morkdown) has stopped working and I find myself wanting it every single day!

So, I've sort of munged the two together, I've butchered your original though so I'm only offering my changes here and not expecting that they'll all be to your taste.

Summary of major changes:
- `me()` is now `Me`, an object to be instantiated.
- Switch out marked & highlightjs on the client to [brucedown](http://github.com/rvagg/node-brucedown) on the server which uses marked + [pygments](http://pygments.org/) to produce near-exact GitHub HTML (there are a couple of very small differences but they are because marked does a _better_ job than Sundown at parsing MD). There's a slight delay in rendering but it's _very_ small and improved by the next point:
- Removed express and gone with vanilla HTML, there's a simple router that uses `this.handle_X()` methods for handling the few dynamic calls. Using [st](https://github.com/isaacs/st) for serving the static content. I was kind of surprised at the  noticeable speed increase of removing express TBH.
- Rewrite the contents of _index.html_ when / is requested so it contains the contents of the requested file and its initial rendered version, so there's no need to separately request it after startup.
- Included basic GitHub'ish CSS styling, including the same colouring rules for pygments HTML.
- Changed layout so the 2 boxes are consistently positioned at different window sizes.

Some screenshots:

morkme1

morkme2

No offence caused if you don't want this, or if you just want to cherry pick bits of it. I'm happy to maintain my own version as a replacement for morkdown if need be.

Have some :cake:

### CODE REVIEW

**Comment by ralphtheninja** [comment]
+1

**Comment by ralphtheninja** [comment]
This is a great improvement! Fixes a lot of scrolling issues etc too. For example I had problems scrolling down to the bottom of the left pane and couldn't edit text at the bottom.

MEEERGE Julian! :)

**Comment by juliangruber** [comment]
@ralphtheninja can you point me to a README where you encountered those scolling issues? +, do you have the latest `me`?

**Comment by ralphtheninja** [comment]
@juliangruber I have problems with any README, for example node-levelup. Using latest master.

**Comment by ralphtheninja** [comment]
Here's a screenshot. As you can see, the left most pane can't be scrolled down further.

readme

**Comment by ralphtheninja** [comment]
Another scrolling issue. If I let the leftmost pane have focus and hit page down, the rendered output is offset wrong from the rightmost pane

pagedown

**Comment by juliangruber** [comment]
could you check out the new version I just released and give me feeback? :)

**Comment by ralphtheninja** [comment]
These commits are after the one that breaks 'me' so I can't test it just yet.

**Comment by juliangruber** [comment]
is there no error?

**Comment by ralphtheninja** [comment]
This commit https://github.com/juliangruber/me/commit/1f466893718cbdb1e3ca86bbd0523cfece7f74e2 breaks me, I can't test these fixes because I can't use me at all.

**Pull request closed without merging**
